print("Hello, world")
print(5+3)
print("python","is","fun!")
print("she said,\"Hello!\"")
print("First line\ nSecond line")
print("item 1\tltem 2\tltem 3")
print("The result is", 42)
print(12345)
print(3.14159)
print("Dollar sign:$")
print("apple","banana","cherry",sep=",")
print("hello,",end="")
print("World!")
print("python!"*3)
print("\u2764")# 
print()
print("Hello"+"World!")
print(True)
print(False)
print(1.2e3)#
print(""" This is multiline print statement. """)
print("This is a backlash:\\")